github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/app-monitoring-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/jprofiler"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   jprofiler
  uses: docker://ghcr.io/paketo-buildpacks/actions/jprofiler-dependency:main
